### get all clients
http://localhost:5269/clients

### get one client
http://localhost:5269/clients/1

### creates a new client
POST http://localhost:5269/clients
Content-Type: application/json

{
    "FirstName": "Spongebob",
    "LastName": "Bob",
    "Age": 80
}

### update a client
PUT http://localhost:5269/clients/1
Content-Type: application/json

{
    "FirstName": "Patrick",
    "LastName": "Bob",
    "Age": 79
}

### delete a client

DELETE http://localhost:5269/clients/1

### get all activities
http://localhost:5269/activities

### get one activity
http://localhost:5269/activities/1

### creates a new activity
POST http://localhost:5269/activities
Content-Type: application/json

{
    "Name": "Koken"
}

### update a activity
PUT http://localhost:5269/activities/1
Content-Type: application/json

{
    "Name": "Boswandeling"
}

### delete a client

DELETE http://localhost:5269/activities/1

### creates a new activity
POST http://localhost:5269/clients/2/activities
Content-Type: application/json

{
  "activityId": 5,
  "rating": 4,
  "participationDate": "2026-01-05T00:00:00",
  "notes": "Client participated actively and showed good motivation."
}

###
GET  http://localhost:5269/clients/2/activities/5
